---
# tasks file for haproxy
- name: install haproxy
  dnf:
          name: haproxy
          state: present

- name: configure haproxy
  template:
          src: haproxy.j2
          dest: /etc/haproxy/haproxy.cfg
  notify: start haproxy
